module.exports = [
  {
    name: 'dev',
    type: 'postgres',
    host: 'localhost',
    port: 5432,
    username: 'test',
    password: 'test',
    database: 'test',
    synchronize: true,
    logging: true,
    entities: ['src/entity/**/*.ts'],
    migrations: ['src/migration/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
  },
  {
    name: 'prod',
    type: 'postgres',
    host: process.env.QOVERY_POSTGRESQL_ZDDD7F0A9_HOST,
    port: process.env.QOVERY_POSTGRESQL_ZDDD7F0A9_PORT,
    username: process.env.QOVERY_POSTGRESQL_ZDDD7F0A9_USER,
    password: process.env.QOVERY_POSTGRESQL_ZDDD7F0A9_PASSWORD,
    database: process.env.QOVERY_POSTGRESQL_ZDDD7F0A9_DATABASE,
    synchronize: true,
    logging: true,
    entities: ['src/entity/**/*.ts'],
    migrations: ['src/migration/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
  },
];
